openai:
  api_key: ""  # 从环境变量OPENAI_API_KEY获取
  base_url: "https://api.ppinfra.com/v3/openai"
  model: "deepseek/deepseek-v3-0324"
  temperature: 0.7
  max_tokens: 2000
  timeout: 30s

mcp:
  timeout: 30s
  servers:
    - name: "ssh-jsonrpc"
      command: "../mcp/go_jsonrpc/build/ssh-mcp-server"
      args: ["-config", "../mcp/go_jsonrpc/config.yaml"]
      description: "基于JSON-RPC实现的SSH MCP服务器"
      enabled: true
    - name: "ssh-sdk"
      command: "../mcp/go-sdk/build/ssh-mcp-server-sdk"
      args: ["-config", "../mcp/go-sdk/config.yaml"]
      description: "基于官方SDK实现的SSH MCP服务器"
      enabled: false

chat:
  max_history: 20
  system_prompt: "你是一个智能运维助手，可以通过MCP工具执行SSH命令和文件操作。请根据用户需求选择合适的工具来完成任务。在执行命令前，请先解释你将要做什么，然后执行相应的工具调用。"
  auto_save: true
  save_path: "./conversations"
  enable_mcp: true
  mcp_auto_call: true

log:
  level: "info"
  file: "/tmp/mcp-openai-chat.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true 