server:
  name: "SSH-MCP-Server-SDK"
  version: "1.0.0"
  protocol_version: "2025-03-26"
  timeout: 30s

ssh:
  default_user: "root"
  default_port: 22
  timeout: 30s
  key_file: ""
  known_hosts_file: ""
  max_connections: 10

log:
  level: "info"
  file: "/tmp/ssh-mcp-server-sdk.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true 